// Build script to generate config.js from environment variables
// This script runs during Netlify build to create config.js from MAPBOX_TOKEN env var

const fs = require('fs');
const path = require('path');

// Get the Mapbox token from environment variable (Netlify sets this)
// Check multiple possible environment variable names
const mapboxToken = process.env.MAPBOX_TOKEN || 
                    process.env.VITE_MAPBOX_TOKEN || 
                    process.env.REACT_APP_MAPBOX_TOKEN ||
                    '';

// Check if we're in a CI/CD environment (like Netlify)
const isCI = process.env.CI === 'true' || process.env.NETLIFY === 'true';

if (!mapboxToken) {
  if (isCI) {
    console.warn('⚠ Warning: MAPBOX_TOKEN environment variable is not set.');
    console.warn('⚠ Mapbox globe will not work on the deployed site.');
    console.warn('⚠ Please set MAPBOX_TOKEN in your Netlify site settings:');
    console.warn('⚠ Site settings > Environment variables > Add variable: MAPBOX_TOKEN');
  } else {
    // In local development, check if config.js already exists
    const configPath = path.join(__dirname, 'config.js');
    if (fs.existsSync(configPath)) {
      console.log('ℹ Local config.js exists and will be used.');
      console.log('ℹ To regenerate, set MAPBOX_TOKEN environment variable and run: npm run build');
      return;
    }
    console.warn('⚠ Warning: MAPBOX_TOKEN not set and no local config.js found.');
    console.warn('⚠ Create config.js manually or set MAPBOX_TOKEN environment variable.');
  }
}

// Generate config.js content
// Escape any single quotes in the token to prevent JavaScript errors
const escapedToken = mapboxToken.replace(/'/g, "\\'");
const configContent = `// Mapbox Configuration
// This file is auto-generated during build from environment variables
// Do not edit this file manually - it will be overwritten on each build
window.MAPBOX_TOKEN = '${escapedToken}';
`;

// Write config.js to the root directory
const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✓ config.js generated successfully');
if (mapboxToken) {
  console.log('✓ Mapbox token configured (length: ' + mapboxToken.length + ' characters)');
} else {
  console.log('⚠ Mapbox token is empty - globe will not display');
}

