// Build script to generate config.js from environment variables
// This script runs during Netlify build to create config.js from MAPBOX_TOKEN env var

const fs = require('fs');
const path = require('path');

// Get the Mapbox token from environment variable (Netlify sets this)
// Check multiple possible environment variable names
const mapboxToken = process.env.MAPBOX_TOKEN || 
                    process.env.VITE_MAPBOX_TOKEN || 
                    process.env.REACT_APP_MAPBOX_TOKEN ||
                    '';

// Check if we're in a CI/CD environment (like Netlify)
const isCI = process.env.CI === 'true' || process.env.NETLIFY === 'true';

// Always generate config.js (even if token is empty for debugging)
// Escape any single quotes in the token to prevent JavaScript errors
const escapedToken = (mapboxToken || '').replace(/'/g, "\\'").replace(/\\/g, "\\\\");
const configContent = `// Mapbox Configuration
// This file is auto-generated during build from environment variables
// Do not edit this file manually - it will be overwritten on each build
window.MAPBOX_TOKEN = '${escapedToken}';
`;

// Write config.js to the root directory
const configPath = path.join(__dirname, 'config.js');
try {
  fs.writeFileSync(configPath, configContent, 'utf8');
  console.log('✓ config.js generated successfully');
  
  if (mapboxToken && mapboxToken.trim() !== '') {
    console.log('✓ Mapbox token configured (length: ' + mapboxToken.length + ' characters)');
    console.log('✓ Token starts with: ' + mapboxToken.substring(0, 10) + '...');
  } else {
    console.warn('⚠ Mapbox token is empty or not set');
    if (isCI) {
      console.warn('⚠ Mapbox globe will not work on the deployed site.');
      console.warn('⚠ Please set MAPBOX_TOKEN in your Netlify site settings:');
      console.warn('⚠ Site settings > Environment variables > Add variable: MAPBOX_TOKEN');
      console.warn('⚠ Make sure to redeploy after adding the variable.');
    } else {
      console.warn('⚠ Set MAPBOX_TOKEN environment variable and run: npm run build');
    }
  }
} catch (error) {
  console.error('✗ Error generating config.js:', error.message);
  process.exit(1);
}

